<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $roleImages = [
            'Controller' => "https://static.wikia.nocookie.net/valorant/images/0/04/ControllerClassSymbol.png",
            'Duelist' => "https://static.wikia.nocookie.net/valorant/images/f/fd/DuelistClassSymbol.png",
            'Sentinel' => "https://static.wikia.nocookie.net/valorant/images/4/43/SentinelClassSymbol.png",
            'Initiator' => "https://static.wikia.nocookie.net/valorant/images/7/77/InitiatorClassSymbol.png",
        ];

        Agent::create([
            'slug' => "brimstone",
            'img' => "../../img/Brimstone_Artwork_Full.png",
            'name' => "Brimstone",
            'role' => "Controller",
            'roleImg' => $roleImages['Controller'],
            'description' => "Joining from the US, Brimstone's orbital weapons ensure his squad is always in a favorable position. His ability to deliver reinforcements with precision and safety makes him an unmatched combat commander.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/d7e00a4ad8a1a01b2edcb9fc1193d05e4e50248f-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/5325b2340045a32d919d467ce3b09c3725de73ea-126x126.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/f6c1e1c587dbfe97a4185a47326ce45c42620583-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8cfa836d1d19356685e42c13054f9f5bc8e9e029-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's1Desc' => "INCENDIARY \n\nREADY the incendiary grenade launcher. SHOOT to launch a grenade that explodes upon reaching the floor, creating a long-lasting fire zone that damages players within the zone.",
            's2Desc' => "SKY SMOKE \n\nSTART the tactical map. SHOOT to determine the landing location of the Brimstone smoke cloud. SHOOT ALT to confirm, launching a long-lasting, vision-obscuring smoke cloud in the selected area.",
            's3Desc' => "STIM BEACON \n\nSTAND OUT a stim beacon. SHOOT to throw a stim beacon in front of Brimstone. When it lands, the stim beacon will create a field that awards Rapid Fire to the player.",
            's4Desc' => "ORBITAL STRIKE \n\nSTART the tactical map. SHOOT to launch a long-lasting orbital strike laser at a selected location, dealing high damage over time to players in the selected area.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "phoenix",
            'img' => "../../img/Phoenix_Artwork_Full.png",
            'name' => "Phoenix",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Hailing from the U.K., Phoenix's star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he's got backup or not, he'll rush into a fight on his own terms.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/beb874d19c79982f0e99e858098c067d9132a95a-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/67df9ca3cb158a945fc9b13eb0e3949683c4c65d-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/d807a982ce70475acb2e8461b4f8737204e35d96-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/d428c0c6c73ba34676e063092a7ae7157268db0c-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "CURVEBALL \n\nEQUIP a flare orb that takes a curving path and detonates shortly after throwing. FIRE to curve the flare orb to the left, detonating and blinding any player who sees the orb. ALTERNATE FIRE to curve the flare orb to the right.",
            's2Desc' => "BLAZE \n\nEQUIP a flame wall. FIRE to create a line of flame that moves forward, creating a wall of fire that blocks vision and damages players passing through it. HOLD FIRE to bend the wall in the direction of your crosshair.",
            's3Desc' => "HEALING ORB \n\nEQUIP a healing orb. FIRE with your crosshairs over a damaged ally to activate a heal-over-time on them. ALT FIRE while Sage's healing orb is equipped to conjure a healing area.",
            's4Desc' => "RUN IT BACK \n\nINSTANTLY place a marker at Phoenix's location. While this ability is active, dying or allowing the timer to expire will end this ability and bring Phoenix back to this location with full health.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "sage",
            'img' => "../../img/Sage_Artwork_Full.png",
            'name' => "Sage",
            'role' => "Sentinel",
            'roleImg' => $roleImages['Sentinel'],
            'description' => "The stronghold. The savior. Life for Sage and her squad is a series of fights to keep each other alive. She creates safety for herself and her team wherever she goes.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/f2931e5af58255216179b21cce81f53eab15d6ee-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/cdc246179e160ded2788fd37ac21f10bc040ad54-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/829075fef7193503dd480947b79d78193d729d42-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/90b6e1ca1a3ecd68e2a3072515d071f80bf46c1d-128x128.png?auto=format&fit=crop&q=80&h=64&w=64&crop=center",
            's1Desc' => "BARRIER ORB \n\nEQUIP a barrier orb. FIRE places a solid wall. ALT FIRE rotates the targeter.",
            's2Desc' => "SLOW ORB \n\nEQUIP a slowing orb. FIRE to throw a slowing orb forward that detonates upon landing, creating a lingering field that slows players caught inside of it.",
            's3Desc' => "HEALING ORB \n\nEQUIP a healing orb. FIRE with your crosshairs over a damaged ally to activate a heal-over-time on them. ALT FIRE while Sage's healing orb is equipped to conjure a healing area.",
            's4Desc' => "RESURRECTION \n\nEQUIP a resurrection ability. FIRE with your crosshairs placed over a dead ally to begin resurrecting them. After a brief channel, the ally will be brought back to life with full health.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "sova",
            'img' => "../../img/Sova_Artwork_Full.png",
            'name' => "Sova",
            'role' => "Initiator",
            'roleImg' => $roleImages['Initiator'], 
            'description' => "Born from the eternal winter of Russia's tundra, Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8ab5a2d03438ff0f8b2ba2d7b26c812ab6b7adbb-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/b428e1783f98a0990b86d13872f564095442f44b-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/07877d7c79546ef64338eae550ffa5649f3582b0-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/7b9f078b0576e87e74b8175b0d33ac682b7a8ab3-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "SHOCK BOLT \n\nEQUIP a bow with a shock bolt. FIRE to send the",
            's2Desc' => "OWL DRONE \n\nEQUIP an owl drone. FIRE to deploy and take control of movement of the drone. While in control of the drone, FIRE to shoot a marking dart. This dart will reveal the location of any player struck by the dart.",
            's3Desc' => "RECON BOLT \n\nEQUIP a bow with a recon bolt. FIRE to send the recon bolt forward, activating upon collision and revealing the location of nearby enemies caught in the line of sight of the bolt. Enemies can destroy this bolt.",
            's4Desc' => "HUNTER'S FURY \n\nEQUIP a bow with three long-range, wall-piercing energy blasts. FIRE to release an energy blast in a line in front of Sova, dealing damage and revealing the location of enemies caught in the line.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "viper",
            'img' => "../../img/Viper_Artwork_Full.png",
            'name' => "Viper",
            'role' => "Controller",
            'roleImg' => $roleImages['Controller'],
            'description' => "The American Chemist, Viper deploys an array of poisonous chemical devices to control the battlefield and choke the enemy's vision. If the toxins don't kill her prey, her mindgames surely will.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/3eba05b8ed1ac69c440d54cec365e537d294be25-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/b1204a1fbcc0e2fced090f18ad18e7587357c783-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/f477dce332e51e53f4e2f565f2d3d868dd2d0df8-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/dab73c2ea877aca79a5bb0b8533d1de4ac07186a-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "POISON CLOUD \n\nEQUIP a gas emitter. FIRE to throw the emitter that perpetually remains throughout the round. RE-USE the ability",
            's2Desc' => "TOXIC SCREEN \n\nEQUIP a gas emitter launcher. FIRE to deploy a long line of gas emitters. RE-USE the ability to create a tall wall of toxic gas at the cost of fuel. This ability can be RE-USED more than once.",
            's3Desc' => "SNAKE BITE \n\nEQUIP a chemical launcher. FIRE to launch a canister that shatters upon hitting the floor, creating a lingering chemical zone that damages and slows enemies.",
            's4Desc' => "VIPER'S PIT \n\nEQUIP a chemical sprayer. FIRE to spray a chemical cloud in all directions around Viper, creating a large cloud that reduces the vision range and maximum health of players inside of it.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "cypher",
            'img' => "../../img/Cypher_Artwork_Full.png",
            'name' => "Cypher",
            'role' => "Sentinel",
            'roleImg' => $roleImages['Sentinel'],
            'description' => "The Moroccan information broker, Cypher is a one-man surveillance network who keeps tabs on the enemy's every move. No secret is safe. No maneuver goes unseen. Cypher is always watching.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/292fbe783ac9e2f638822c5f87f09b005b48a712-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/eae012cb583a41bbc0de83f0963a40de58f5534f-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/df43766f56e1e844ed1b179722c9444a1bd1d45c-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/3e8e1779afeebd0612c019f8b2d41d7a984781b3-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "TRAPWIRE \n\nEQUIP a trapwire. FIRE to place a destructible and covert tripwire at the targeted location. RE-USE the ability to create a tripwire that spans between two placed tripwires.",
            's2Desc' => "CYBER CAGE \n\nEQUIP a cyber cage. FIRE to toss the cyber cage in front of Cypher. ACTIVATE to create a zone that blocks vision and slows enemies who pass through it. Look at a trapwire in range to highlight it, and",
            's3Desc' => "TRAPWIRE\n\nEQUIP a trapwire. FIRE to place a destructible and covert tripwire at the targeted location creating a line that spans between the placed location and the wall opposite.",
            's4Desc' => "NEURAL THEFT \n\nINSTANTLY use on a dead enemy player in your crosshairs to reveal the location of all living enemy players.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "reyna",
            'img' => "../../img/Reyna_Artwork_Full.png",
            'name' => "Reyna",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Forged in the heart of Mexico, Reyna dominates single combat, popping off with each kill she scores. Her capability is only limited by her raw skill, making her highly dependent on performance.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/62dc726ff81568e4500167d0d402e0b083c507d9-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/a9ca2fbba6c3f00e1a07e3514ac6a8f107e43e17-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/9d295b17382acbc17bdb4e45e0be74d58e94e6c5-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/daf434a1a75cee1f52309b2cf4eb8f878d07b419-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "DEVOUR \n\nEnemies killed by Reyna leave behind Soul Orbs that last 3 seconds. INSTANTLY consume a nearby soul orb, rapidly healing for a short duration. Health gained through this skill exceeding 100 will decay over time.",
            's2Desc' => "DISMISS \n\nINSTANTLY consume a nearby soul orb, becoming intangible for a short duration. If EMPRESS is active, also become invisible.",
            's3Desc' => "LEER \n\nEQUIP an ethereal destructible eye. ACTIVATE to cast the eye a short distance forward. The eye will Nearsight all enemies who look at it.",
            's4Desc' => "EMPRESS \n\nINSTANTLY enter a frenzy, increasing firing speed, equip and reload speed dramatically. Scoring a kill renews the duration.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "killjoy",
            'img' => "../../img/Killjoy_Artwork_Full.png",
            'name' => "Killjoy",
            'role' => "Sentinel",
            'roleImg' => $roleImages['Sentinel'],
            'description' => "The genius of Germany. Killjoy secures the battlefield with ease using her arsenal of inventions. If the damage from her gear doesn't stop her enemies, her robots' debuff will help make short work of them.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/d86a84fcd7cc656fec66be28d496a56b5171dd52-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/6fcb1a4dfb49ad8fabae929bc5aea5240ddb42ac-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/4ca9c7f4a85e5e454d8d9638247bd36cab1d4124-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/d7d7787df75af327d171b723a262172693125dc4-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "ALARMBOT \n\nEQUIP a covert Alarmbot. FIRE to deploy a bot that hunts down enemies that get in range. After reaching its target, the bot explodes, applying Vulernable. HOLD EQUIP to recall a deployed bot.",
            's2Desc' => "TURRET \n\nEQUIP a Turret. FIRE to deploy a turret that fires at enemies in a 180 degree cone. HOLD EQUIP to recall the deployed turret.",
            's3Desc' => "NANOSWARM \n\nEQUIP a Nanoswarm grenade. FIRE to throw the grenade. Upon landing, the Nanoswarm goes covert. ACTIVATE the Nanoswarm to deploy a damaging swarm of nanobots.",
            's4Desc' => "LOCKDOWN \n\nEQUIP the Lockdown device. FIRE to deploy the device. After a long windup, the device Detains all enemies caught in the radius. The device can be destroyed by enemies.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "breach",
            'img' => "../../img/Breach_Artwork_Full.png",
            'name' => "Breach",
            'role' => "Initiator",
            'roleImg' => $roleImages['Initiator'],
            'description' => "Breach, the bionic Swede, fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/cca58acc93956ee755ccea171a36584a402793c2-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/668ca53aca3c788f4b9ef8ad35e86979b84745db-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/2621c00e27da47f6a57772902c7806a7bfe0eb66-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/58784f89733dfe25c41f8ba950c6eb4c46507d63-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "FLASHPOINT \n\nEQUIP a blinding charge. FIRE the charge to set fast-acting burst through the wall. The charge detonates to blind all players looking at it.",
            's2Desc' => "FAULT LINE \n\nEQUIP a seismic blast. HOLD FIRE to increase the distance. RELEASE to set off the quake, dazing all players in its zone and in a line up to the zone.",
            's3Desc' => "AFTERSHOCK \n\nEQUIP a fusion charge. FIRE the charge to set a slow-acting burst through the wall. The burst does heavy damage to anyone caught in its area.",
            's4Desc' => "ROLLING THUNDER \n\nEQUIP a seismic charge. FIRE to send a cascading quake through all terrain in a large cone. The quake dazes and knocks up anyone caught in it.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "omen",
            'img' => "../../img/Omen_Artwork_Full.png",
            'name' => "Omen",
            'role' => "Controller",
            'roleImg' => $roleImages['Controller'],
            'description' => "A phantom of a memory, Omen hunts in the shadows. He renders enemies blind, teleports across the field, then lets paranoia take hold as his foe scrambles to learn where he might strike next.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/e8544e323a51c9b8ff7ae8fca257e038a570819d-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/e4012aeda506a8e77f2e83d48aa8c5c73a37b659-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/2790998724c94f38688c9c6c5d43c0712cae18ef-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/fed58cd5eb95f4e50b7b8230a150c3b686b82f78-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "PARANOIA \n\nINSTANTLY fire a shadow projectile forward, briefly reducing the vision range of all players it touches. This projectile can pass straight through walls.",
            's2Desc' => "DARK COVER \n\nEQUIP a shadow orb and enter a phased world to place it. PRESS the ability key to throw it, creating a long-lasting vision-blocking sphere. HOLD FIRE to extend range, ALT FIRE to shorten it, and RELOAD to toggle targeting view.",
            's3Desc' => "SHROUDED STEP \n\nEQUIP a shadow walk ability and see its range indicator. FIRE to begin a brief channel, then teleport to the marked location.",
            's4Desc' => "FROM THE SHADOWS \n\nEQUIP a tactical map. FIRE to begin teleporting to the selected location. While teleporting, Omen will appear as a Shade that can be destroyed by an enemy to cancel his teleport.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "jett",
            'img' => "../../img/Jett_Artwork_Full.png",
            'name' => "Jett",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Representing her home country of South Korea, Jett's agile and evasive fighting style lets her take risks no one else can. She runs circles around every skirmish, cutting enemies before they even know what hit them.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/a0c72fe005e2f87f60f38fdb440569271c51a8fb-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/18cb69683c16d11590eda4c5458a7025f0667895-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8c5e94bfc817e5d35eca7692fd242404de5ac5dd-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8d8e6c956af64b241e49e3625b3cb02fcc61eb09-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "UPDRAFT \n\nINSTANTLY propel Jett high into the air.",
            's2Desc' => "TAILWIND \n\nACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward. Tailwind charge resets every two kills.",
            's3Desc' => "CLOUDBURST \n\nINSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
            's4Desc' => "BLADE STORM \n\nEQUIP a set of highly accurate throwing knives. FIRE to throw a single knife and recharge knives on a kill. ALT FIRE to throw all remaining daggers but does not recharge on a kill.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "raze",
            'img' => "../../img/Raze_Artwork_Full.png",
            'name' => "Raze",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Raze explodes out of Brazil with her big personality and big guns. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of boom.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/ce6b40ccaa79e226c9d5e237af6739dfe412b948-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/4751e0f887099484e0c39c69d7d4762b782e99f8-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/5ab8a4e5cf6d7229021e6cfe8b50a03543c5978f-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/9a02bebe0a944ad2f2c764a0df1dfc8a1e7757fa-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "BLAST PACK \n\nINSTANTLY throw a Blast Pack that will stick to surfaces. RE-USE the ability after deployment to detonate, damaging and moving anything hit. Raze isn't damaged by this ability, but will still take fall damage if launched up far enough.",
            's2Desc' => "PAINT SHELLS \n\nEQUIP a cluster grenade. FIRE to throw the grenade, which does damage and creates sub-munitions, each doing damage to anyone in their range. ALT FIRE to lob. Paint Shells charge resets every two kills.",
            's3Desc' => "BOOM BOT \n\nEQUIP a Boom Bot. FIRE will deploy the bot, causing it to travel in a straight line on the ground, bouncing off walls. The Boom Bot will lock on to any enemies in its frontal cone and chase them, exploding for heavy damage if it reaches them.",
            's4Desc' => "SHOWSTOPPER \n\nEQUIP a rocket launcher. FIRE to shoot a rocket that does massive area damage on contact with anything.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "skye",
            'img' => "../../img/Skye_Artwork_Full.png",
            'name' => "Skye",
            'role' => "Initiator",
            'roleImg' => $roleImages['Initiator'],
            'description' => "Hailing from Australia, Skye and her band of beasts trail-blaze the way through hostile territory. With her creations hampering the enemy, and her power to heal others, the team is strongest and safest by Skye’s side.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/b905a3a39bc979bc43653eccf9fdb289b03c5223-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/ed6e5f91be20274ff84cb24644c3b559bfa8fed1-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/b80c38c49a8e37d69cda3bf335c885170975b415-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/9ccbd11eadca50047c6e84125285a11e1d334acd-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "Trailblazer EQUIP a Tasmanian tiger trinket. FIRE to send out and take control of the predator. While in control, FIRE to leap forward, exploding in a concussive blast and damaging directly hit enemies.",
            's2Desc' => "Guiding Light \n\nEQUIP a hawk trinket. FIRE to send it forward, HOLD FIRE to guide it. RE-USE mid-flight to transform it into a flash, with a hit confirm if an enemy is in range and line of sight.",
            's3Desc' => "Regrowth \n\nEQUIP a healing trinket. HOLD FIRE to channel, healing allies in range and line of sight. Can be reused until her healing pool is depleted. Skye cannot heal herself.",
            's4Desc' => "Seekers \n\nEQUIP a Seeker trinket. FIRE to send out three Seekers to track down the three closest enemies. If a Seeker reaches its target, it Nearsights them. Enemies can destroy the Seekers.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "yoru",
            'img' => "../../img/Yoru_Artwork_Full.png",
            'name' => "Yoru",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Japanese native, Yoru, rips holes straight through reality to infiltrate enemy lines unseen. Using deception and aggression in equal measure, he gets the drop on each target before they know where to look.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/ea733bf224ae53e8e53cabfae19bfc12ce9fcda3-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/580f94ecab50ae7c01279dcd0adb86f9c65362c3-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/43416e5b34cd80c691ed0cc3b69fc73fae93f923-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/51e64df7500b3114c76e5e86dfea2e622bb438e5-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "BLINDSIDE \n\nEQUIP to rip an unstable dimensional fragment from reality. FIRE to throw the fragment, activating a flash that winds up once it collides with a hard surface in world.",
            's2Desc' => "GATECRASH \n\nEQUIP a rift tether FIRE to send the tether forward. ALT FIRE to place a stationary tether. ACTIVATE to teleport to the tether's location. USE to trigger a fake teleport.",
            's3Desc' => "FAKEOUT \n\nEQUIP an echo that becomes Yoru’s mirror image. FIRE to activate and send it forward. ALT FIRE to place an inactive echo, then USE to activate it. Mirror images explode in a blinding flash when destroyed by enemies.",
            's4Desc' => "DIMENSIONAL DRIFT \n\nEQUIP a mask that can see between dimensions. FIRE to drift into Yoru's dimension, unable to be affected or seen by enemies from the outside. REACTIVATE to exit Yoru's dimension early.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "astra",
            'img' => "../../img/Astra_Artwork_Full.png",
            'name' => "Astra",
            'role' => "Controller",
            'roleImg' => $roleImages['Controller'],
            'description' => "Ghanaian Agent Astra harnesses the energies of the cosmos to reshape battlefields to her whim. With full command of her astral form and a talent for deep strategic foresight, she's always eons ahead of her enemy's next move.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/c68e59e5036f302959366885133e4ab4850bb650-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/fe8a6fdb673e9f5a94c3379bde8e78aa9ec7c6c1-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/6c53596bfc3c04a16087fd4553b03c1449d84987-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/1e6ad40dac4f0e475a055b96864a4d5c1eabf34e-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "NOVA PULSE \n\nPlace Stars in Astral Form. ACTIVATE a Star to detonate a Nova Pulse. The Nova Pulse charges briefly then strikes, concussing all players in its area.",
            's2Desc' => "NEBULA \n\nPlace Stars in Astral Form. ACTIVATE to turn a Star into a Nebula (smoke). USE to Dissipate, creating a brief fake Nebula before retrieving the Star for redeployment.",
            's3Desc' => "GRAVITY WELL \n\nPlace Stars in Astral Form (X) ACTIVATE a Star to form a Gravity Well. Players in the area are pulled toward the center before it explodes, making all players still trapped inside Vulnerable.",
            's4Desc' => "ASTRAL FORM / COSMIC DIVIDE \n\nWhen Cosmic Divide is charged, use ALT FIRE to aim, then FIRE to create a barrier blocking bullets and dampening sound.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "kayo",
            'img' => "../../img/Kayo_Artwork_Full.png",
            'name' => "Kay/o",
            'role' => "Initiator",
            'roleImg' => $roleImages['Initiator'],
            'description' => "KAY/O is a machine of war built for a single purpose: neutralizing radiants. His power to Suppress enemy abilities dismantles his opponents' capacity to fight back, securing him and his allies the ultimate edge.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/92fedb7a8c812df29cbaa2390aa07561fe2d89da-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/6771e933554434541c91d58749aa0bbda58619e1-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/40a6811eadf8b794b94e2b40695e14b7c36281a8-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/dabcf9f31c4b63cb2c2e537655ca0cc3b6e08d24-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "FLASH/DRIVE \n\nEQUIP a flash grenade. FIRE to overhand throw. ALT FIRE to lob a weaker version that explodes quickly. The flash grenade explodes after a short fuse, Blinding anyone in line of sight.",
            's2Desc' => "ZERO/POINT \n\nEQUIP a suppression blade. FIRE to throw. The blade sticks to the first surface it hits, winds up, and Suppresses anyone in the radius of the explosion. Enemies can destroy this blade.",
            's3Desc' => "FRAG/MENT \n\nEQUIP an explosive fragment. FIRE to throw. The fragment sticks to the floor and explodes multiple times, dealing near lethal damage at the center with each explosion.",
            's4Desc' => "NULL/CMD \n\nINSTANTLY overload with polarized radianite energy that pulses from KAY/O in a massive radius. Enemies hit with pulses are Suppressed for a short duration. While overloaded, KAY/O gains Combat Stim and can be re-stabilized if downed.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "chamber",
            'img' => "../../img/Chamber_Artwork_Full.png",
            'name' => "Chamber",
            'role' => "Sentinel",
            'roleImg' => $roleImages['Sentinel'],
            'description' => "Well-dressed and well-armed, French weapons designer Chamber expels aggressors with deadly precision. He leverages his custom arsenal to hold the line and pick off enemies from afar, with a contingency built for every plan.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/d8a0105305eefcd44c6c5c823bc6638c18d3850c-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/53b23071d96ffa2d27b73c5edb6ba8b0cf1dc30a-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/6070c2db4a22931c24ff59349664a0c666a777c3-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/b2f83e29d7ff8fbc59aa568eca0ed82d30ab007f-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "HEADHUNTER \n\nACTIVATE to equip a heavy pistol. ALT FIRE with the pistol equipped to aim down sights.",
            's2Desc' => "RENDEZVOUS \n\nEQUIP a teleport anchor. FIRE to place it on the ground. While on the ground and in range of the anchor, REACTIVATE to quickly teleport to the anchor. The anchor can be picked up to be REDEPLOYED.",
            's3Desc' => "TRADEMARK \n\nEQUIP a trap that scans for enemies. FIRE to place it on the ground. When a visible enemy comes in range, the trap counts down and then destabilizes the terrain around them.",
            's4Desc' => "TOUR DE FORCE \n\nACTIVATE to summon a powerful, custom sniper rifle that will kill an enemy with any direct hit to the upper body. ALT FIRE to aim down sights. Killing an enemy creates a lingering field that Slows players caught inside of it.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "neon",
            'img' => "../../img/Neon_Artwork_Full.png",
            'name' => "Neon",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Filipino Agent Neon surges forward at shocking speeds, discharging bursts of bioelectric radiance as fast as her body generates it. She races ahead to catch enemies off guard, then strikes them down quicker than lightning.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/fe17f22ec96403cf3b58b707db4f8e77531a47a6-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/2bfcbc821895e8d01a4f17e8f045dabf24c052e0-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/46c16f398d28f7e029f42bc742f3838443e8a3d3-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/6a0012b92eba95e42828411c1e58d8d1c6420a5f-256x256.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "RELAY BOLT \n\nINSTANTLY throw an energy bolt that bounces once. Upon hitting each surface, the bolt electrifies the ground below with a concussive blast.",
            's2Desc' => "HIGH GEAR \n\nINSTANTLY channel Neon’s power for increased speed. When charged, ALT FIRE to trigger an electric slide. Slide charge resets every two kills.",
            's3Desc' => "FAST LANE \n\nFIRE two energy lines forward on the ground that extend a short distance or until they hit a surface. The lines rise into walls of static electricity that block vision and damage enemies passing through them.",
            's4Desc' => "OVERDRIVE \n\nUnleash Neon’s full power and speed for a short duration. FIRE to channel the power into a deadly lightning beam with high movement accuracy. The duration resets on each kill.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "fade",
            'img' => "../../img/Fade_Artwork_Full.png",
            'name' => "Fade",
            'role' => "Initiator",
            'roleImg' => $roleImages['Initiator'],
            'description' => "Turkish bounty hunter, Fade, unleashes the power of raw nightmares to seize enemy secrets. Attuned with terror itself, she hunts targets and reveals their deepest fears—before crushing them in the dark.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8f34a932e08cdc5e6472b445f5c2dc150228eda7-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/272ae63510fddab9fa751f59349def5bd09a40b2-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/0389b190631d8c27a09e147070aab4b706113959-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/7ba7b49c678cfcf07564ab57907c60636bb916b0-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "SEIZE \n\nEquip a nightmare ink orb. FIRE to throw it, causing it to drop and explode on impact, trapping enemies inside. RE-USE to drop it early.",
            's2Desc' => "HAUNT \n\nEquip a nightmarish entity. FIRE to throw it, letting it drop and transform upon impact, revealing enemies in sight. Enemies can destroy it. RE-USE to drop early.",
            's3Desc' => "PROWLER \n\nEquip a Prowler. FIRE to send it forward in a straight line. It locks onto enemies or trails, chasing and nearsighting them on contact. HOLD FIRE to steer it.",
            's4Desc' => "NIGHTFALL \n\nEQUIP the power of Fear. FIRE to send out a wave of nightmare energy that can traverse through walls. The energy creates a trail to the opponent as well as deafens and decays them.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "harbor",
            'img' => "../../img/Harbor_Artwork_Full.png",
            'name' => "Harbor",
            'role' => "Controller",
            'roleImg' => $roleImages['Controller'],
            'description' => "Hailing from India’s coast, Harbor storms the field wielding ancient technology with dominion over water. He unleashes frothing rapids and crushing waves to shield his allies, or pummel those that oppose him.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/e988e2cc973a4c6791db0b87c13ce6a02162ed89-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/e6af3e9f6f2259ffe3c69448adc9f89beebc4f80-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/88032d13dc1b40e61bc763749c5aae29a056735d-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8fb4f759e45fdfb5c6888a456ef6ec5e027ad052-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "COVE \n\nEQUIP a sphere of shielding water. FIRE to throw. ALT FIRE to underhand throw. Upon impacting the ground, spawn a destructible water shield that blocks bullets.",
            's2Desc' => "HIGH TIDE \n\nEquip a water wall. FIRE to send it forward along the ground. HOLD FIRE to guide its path. ALT FIRE to stop it early. Players hit are slowed.",
            's3Desc' => "CASCADE \n\nEQUIP a wave of water. FIRE to send the wave rolling forward and through walls. RE- USE to stop the wave. Players hit are SLOWED.",
            's4Desc' => "RECKONING \n\nEQUIP the full power of your Artifact. FIRE to summon a geyser pool on the ground. Enemy players in the area are targeted by successive geyser strikes. Players caught within a strike are CONCUSSED.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "gekko",
            'img' => "../../img/Gekko_Artwork_Full.png",
            'name' => "Gekko",
            'role' => "Initiator",
            'roleImg' => $roleImages['Initiator'],
            'description' => "Gekko the Angeleno leads a tight-knit crew of calamitous creatures. His buddies bound forward, scattering enemies out of the way, with Gekko chasing them down to regroup and go again.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/0be9c33b718eb7f941890558e661f147802cf762-256x236.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/5cd2d39b6747b897e6648172d084d355477ea545-255x248.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/6a9ead27349e4fa318bc426ac57f9addb2ecf143-252x175.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/589f75f0e50a8c1c465e2bf95599d140c52c69f4-254x241.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "WINGMAN \n\nEquip Wingman. FIRE to send him forward to seek enemies and unleash a concussive blast at the first target. ALT FIRE on a Spike site or planted Spike to make him plant or defuse",
            's2Desc' => "DIZZY \n\nEQUIP Dizzy FIRE to send Dizzy soaring forward through the air. Dizzy charges then unleashes plasma blasts at enemies in line of sight. Enemies hit by her plasma are blinded.",
            's3Desc' => "MOSH PIT \n\nEQUIP Mosh FIRE to throw Mosh like a grenade ALT FIRE to throw underhand. Upon landing Mosh duplicates across a large area then after a short delay explodes.",
            's4Desc' => "THRASH \n\nEQUIP Thrash FIRE to send Thrash forward. Thrash charges then unleashes a series of plasma blasts at enemies in line of sight. Enemies hit by his plasma are concussed.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "deadlock",
            'img' => "../../img/Deadlock_Artwork_Full.png",
            'name' => "Deadlock",
            'role' => "Sentinel",
            'roleImg' => $roleImages['Sentinel'],
            'description' => "Norwegian operative Deadlock deploys an array of cutting-edge nanowire to secure the battlefield from even the most lethal assault. No one escapes her vigilant watch, nor survives her unyielding ferocity.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/3abe232b9adae7ae2d96a5b87d0a4fecb8a3bd5a-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/f712588876f0df7fa899418b4f2b2b6fbccfedbf-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/4516d714505d1a69918c8405dda463aeb7c5718b-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/fba13a9ca1a5efb4e3456b96c0e78cbf4b3ec46d-512x512.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "SONIC SENSOR \n\nEQUIP a Sonic Sensor. FIRE to deploy. The sensor monitors an area for enemies making sound. It concusses that area if footsteps, weapons fire, or significant noise are detected.",
            's2Desc' => "BARRIER MESH \n\nEQUIP a Barrier Mesh disc. FIRE to throw forward. Upon landing, the disc generates barriers from the origin point that block character movement.",
            's3Desc' => "GRAVNET \n\nEQUIP a GravNet grenade. FIRE to throw. ALT FIRE to lob the grenade underhand. The GravNet detonates upon landing, forcing any enemies caught within to crouch and move slowly.",
            's4Desc' => "ANNIHILATION \n\nEQUIP a Nanowire Accelerator. FIRE to unleash a pulse of nanowires that captures the first enemy contacted. The cocooned enemy is pulled along a nanowire path and will die if they reach the end.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "iso",
            'img' => "../../img/Iso_Artwork_Full.png",
            'name' => "Iso",
            'role' => "Duelist",
            'roleImg' => $roleImages['Duelist'],
            'description' => "Chinese fixer for hire, Iso falls into a flow state to dismantle the opposition. Reconfiguring ambient energy into bulletproof protection, he advances with focus towards his next duel to the death.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/5b981e9b6c35a518177ff1c7170a213e36f393c7-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/ac58844d85858401edcefdb8e38ec23bfb672481-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/2439fd36c37debf4bd082c0609b356733577de04-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/67aa0a3de742de9793d4b1fbfae38961c8d0076f-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "UNDERCUT \n\nEQUIP a molecular bolt. Fire to throw it forward, applying a brief FRAGILE to all players it touches. The bolt can pass through solid objects, including walls.",
            's2Desc' => "DOUBLE TAP \n\nSTART a focus timer. Once completed, enter a flow state during which downed enemies you kill or damage generate an energy orb. Shooting this orb grants you a shield which absorbs one instance of damage from any source.",
            's3Desc' => "CONTINGENCY \n\nEQUIP to assemble prismatic energy. FIRE to push an indestructible wall of energy forward that blocks bullets.",
            's4Desc' => "KILL CONTRACT \n\nEQUIP an interdimensional arena. FIRE to hurl a column of energy through the battlefield, pulling you and the first enemy hit into the arena. You and your opponent duel to the death.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "clove",
            'img' => "../../img/Clove_Artwork_Full.png",
            'name' => "Clove",
            'role' => "Controller",
            'roleImg' => $roleImages['Controller'],
            'description' => "Scottish troublemaker Clove makes mischief for enemies in both the heat of combat and the cold of death. The young immortal keeps foes guessing, even from beyond the grave, their return to the living only ever a moment away.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/b193ce03089f357e330a51876dbb7172444e80da-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/5ce846ce8e5ae7ce7904f0c31824f7729307743e-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/8207dec024cbac83685eb14379055e25d8c3bbed-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data/cb541873b62077199333f468fddd54620635870a-128x128.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "Meddle \n\nEQUIP a fragment of immortality essence. FIRE to throw the fragment, which erupts after a short delay and temporarily decays all targets caught inside.",
            's2Desc' => "Ruse \n\nEQUIP to view the battlefield. FIRE to set the locations where Clove’s clouds will settle. ALT FIRE to confirm, launching clouds that block vision in the chosen areas. Clove can use this ability after death.",
            's3Desc' => "Pick-Me-Up \n\nINSTANTLY absorb the life force of a fallen enemy that Clove damaged or killed, gaining haste and temporary health.",
            's4Desc' => "Not Dead Yet \n\nAfter dying, ACTIVATE to resurrect. Once resurrected, Clove must earn a kill or a damaging assist within a set time or they will die.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Agent::create([
            'slug' => "vyse",
            'img' => "../../img/Vyse_Artwork_Full.png",
            'name' => "Vyse",
            'role' => "Sentinel",
            'roleImg' => $roleImages['Sentinel'],
            'description' => "Metallic mastermind Vyse unleashes liquid metal to isolate, trap, and disarm her enemies. Through cunning and manipulation, she forces all who oppose her to fear the battlefield itself.",
            's1Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/news/665d8820138b5d817a7f6f6522e983edd1ea9df7-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's2Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/news/f0ac7fb5d31a65820bcc22217abcafbbfb4077e7-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's3Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/news/3a3e90a9b09ba95e7aed7b3f5979ed88d62d2785-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's4Img' => "https://cmsassets.rgpub.io/sanity/images/dsfx7636/news/d67be7669c8a4b483305cf7501c27c25adb44236-1024x1024.png?auto=format&fit=crop&q=80&h=48&w=48&crop=center",
            's1Desc' => "Shear \n\nEQUIP filaments of liquid metal. FIRE to place a hidden wall trap. When an enemy crosses, an indestructible wall bursts from the ground behind them. The wall lasts for a brief time before dissipating.",
            's2Desc' => "Arc Rose \n\nEQUIP an Arc Rose. Target a surface and FIRE to place a stealthed Arc Rose, or ALT Fire to place the Arc Rose through it. REUSE to blind all players looking at it. This ability can be picked up to be REDEPLOYED.",
            's3Desc' => "Razorvine \n\nEQUIP a nest of liquid metal. FIRE to launch. Upon landing, the nest becomes invisible. When ACTIVATED, it sprawls out into a large razorvine nest which slows and damages all players who move through it.",
            's4Desc' => "Steel Garden \n\nEQUIP a bramble of liquid metal. FIRE to send the metal erupting from you as a torrent of metal thorns, JAMMING enemy primary weapons after a brief windup.",
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        // Agent::create([
        //     'slug' => "",
        //     'img' => "",
        //     'name' => "",
        //     'role' => "",
        //     'roleImg' => "",
        //     'description' => "",
        //     's1Img' => "",
        //     's2Img' => "",
        //     's3Img' => "",
        //     's4Img' => "",
        //     's1Desc' => "",
        //     's2Desc' => "",
        //     's3Desc' => "",
        //     's4Desc' => "",
        //     'created_at' => now(),
        //     'updated_at' => now(),
        // ]);
    }
}
